# .streamlit/secrets.toml

azure_openai_api_key = "0623fbb60f594a8da0d22c678ae54412"
azure_openai_endpoint = "https://uspceastus1824278042.openai.azure.com/openai/deployments/uspc-gpt4omini-eastus/chat/completions?api-version=2023-03-15-preview"
azure_openai_deployment_name = "text-davinci-003"